<?php

use App\Models\MaintenanceRequest;
use App\Models\PreventiveMaintenanceLog;
use App\Models\PreventiveMaintenancePlan;
use App\Models\WorkOrder;
use App\Services\ActivityLogger;
use App\Http\Controllers\Api\SparePartRequestController;
use Illuminate\Foundation\Inspiring;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Schedule;

Artisan::command('inspire', function () {
    $this->comment(Inspiring::quote());
})->purpose('Display an inspiring quote');

Artisan::command('maintenance:process-due', function () {
    $duePlans = PreventiveMaintenancePlan::query()
        ->where('status', 'active')
        ->whereDate('next_due_date', '<=', now()->toDateString())
        ->get();

    $count = 0;
    foreach ($duePlans as $plan) {
        $workOrder = WorkOrder::create([
            'request_id' => null,
            'created_by' => $plan->created_by,
            'assigned_to' => $plan->assigned_technician_id,
            'priority' => $plan->priority,
            'scheduled_date' => $plan->next_due_date,
            'estimated_hours' => $plan->estimated_hours,
            'work_status' => 'assigned',
        ]);

        PreventiveMaintenanceLog::create([
            'plan_id' => $plan->id,
            'work_order_id' => $workOrder->id,
            'performed_at' => null,
            'notes' => 'Auto-generated by scheduler.',
            'created_at' => now(),
        ]);

        $plan->next_due_date = $plan->calculateNextDueDate()->toDateString();
        $plan->save();

        ActivityLogger::log(null, 'preventive_maintenance', 'trigger', $plan->id, "Auto-triggered PM plan #{$plan->id}.", null);
        $count++;
    }

    $updated = MaintenanceRequest::query()
        ->whereNotIn('status', ['completed', 'closed', 'rejected'])
        ->whereNotNull('due_date')
        ->where('due_date', '<', now())
        ->update(['is_overdue' => true]);

    $this->info("Generated {$count} PM work orders and marked {$updated} requests overdue.");
})->purpose('Generate due preventive work orders and apply SLA overdue flags.');

Schedule::command('maintenance:process-due')->hourly();
Schedule::command('alerts:send-operational-emails')->hourly();

Artisan::command('spare-part-requests:expire', function () {
    $controller = app(SparePartRequestController::class);
    $count = $controller->processExpirations();
    $this->info("Expired {$count} spare part requests.");
})->purpose('Auto-expire approved spare part requests past pickup deadline.');

Schedule::command('spare-part-requests:expire')->everyFifteenMinutes();
